server:
  servlet:
    session:
      timeout: 60m
    context-path: /postgraduate
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/postgraduate_help?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:static/,file:static/

mybatis-plus:
  configuration:

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'null'
    cache-enabled: false
    call-setters-on-nulls: true
  global-config:
    db-config:
      logic-delete-field: del_falg
      logic-delete-value: 0
      logic-not-delete-value: 1
      id-type: auto

    refresh-mapper: true  #热加载mapper.xml 不用每次修改xml文件后都重启

    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  mapper-locations: classpath*:mapper/*.xml

  type-aliases-package: com.qing.entity


